### ISSUE TITLE
Subtopic links are not working

### ISSUE THREAD

**Issue by somindatommy** [wso2/docs-is#689] opened 2019-10-30 01:58 UTC
**Description:**
Navigate to page [1], click on the links and it will not navigate to the corresponding subtopic. This seems to an error in all the places like this. Therefore, this needs to be fixed in doc [1] and other docs.

[1] - https://is.docs.wso2.com/en/5.9.0/setup/token-persistence/

**Suggested Labels:**
DOC, IS 5.9.0, IS 5.10.0

**Comment by deshankoswatte** [comment] 2019-11-22 12:06
Cannot reproduce. Therefore, closing the issue.

**Closed** 2019-11-22 12:07 UTC
